apiVersion: v1
kind: PersistentVolume
metadata:
  name: de-face
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /var/nfs/general
    server: 128.84.48.178
    readOnly: false
