kind: Service
apiVersion: v1
metadata:
  name: de-inference-service-frontend
spec:
  selector:
    app: de-inference-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: NodePort