kind: Service
apiVersion: v1
metadata:
  name: de-frontend-service
spec:
  selector:
    app: de-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 31468
  type: NodePort
